#!/bin/sh

# usage:
# to generate makefiles for non-debug build, run "./build_makefiles"
# to generate makefiles for debug build, run "./build_makefiles LW_DEBUG"

echo "./gendocs"
./gendocs

echo "autoreconf -ifv"
autoreconf -ifv

if [ "$#" -eq 1 ] && [ "$1" = "LW_DEBUG" ]; then
    echo "./configure --enable-debug"
    CFLAGS="-O0 -g -Wall -Werror" ./configure --enable-debug
else
    echo "./configure"
    ./configure
fi
