#!/bin/sh
./gitlog-to-changelog.pl >& ChangeLog

#txt2tags -t html --mask-email -i README.t2t -o index.html
txt2tags -t html -i README.t2t -o index.html
txt2tags -t html -i FOOTER.t2t -o authors.html
txt2tags -t html -i FAQ.t2t -o faq.html
txt2tags -t html -i NEWSLOG.t2t -o news.html
txt2tags -t html -i EXAMPLE.t2t -o example.html

#txt2tags -t txt --mask-email -i README.t2t -o README
txt2tags -t txt -i README.t2t -o README
txt2tags -t txt -i FOOTER.t2t -o AUTHORS
txt2tags -t txt -i FAQ.t2t -o FAQ
txt2tags -t txt -i NEWSLOG.t2t -o NEWS
txt2tags -t txt -i EXAMPLE.t2t -o EXAMPLE
