#!/bin/sh
echo "rm ChangeLog"
rm ChangeLog

echo "rm *.html"
rm *.html

echo "rm README"
rm README
echo "rm AUTHORS"
rm AUTHORS
echo "rm FAQ"
rm FAQ
echo "rm NEWS"
rm NEWS
echo "rm EXAMPLES"
rm EXAMPLES
